#ifndef ARREDITORDEFINES

#define ARREDITORDEFINES

#define ARRMENU_START MENU_ID_START+50
#define FX_POPSELECTAUTO_ID (ARRMENU_START+1205)

// Gadgets -------------------------------------------
enum TrackGadget{
	FX_MIDIOUT_ID=GADGET_ID_START+50,
	FX_INFILTER_ID,
	FX_MIDITYPE_ID,
	FX_AUDIOIN_ID,
	FX_QUANTIZE_ID ,
	FX_TRACKNAME_ID,
	FX_CAPTURE_ID,
	FX_NOTEON_ID,
	FX_NOTEOFF_ID,
	FX_MIDICHANNEL_ID,
	FX_MIDITHRU_ID,
	FX_MIDIPROGRAM_ID,
	FX_AUDIOMIXER_ID,
	FX_PATTERNAME_ID,
	FX_PATTERQUANTIZE_ID,
	FX_PATTERNMIDICHANNEL_ID ,
	FX_PATTERNLOOP_ID,
	FX_PATTERNMUTE_ID ,
	FX_TRANSPOSE_ID ,
	FX_VELOCITY_ID ,
	FX_PATTERNVELOCITY_ID ,
	FX_PATTERNTRANSPOSE_ID ,
	FX_MIDIIN_ID,
	FX_FILTER_ID ,
	FX_DELAY_ID ,
	FX_PATTERNBANKSELECT_ID,
	FX_PATTERNLOOPNUMBER_ID,
	FX_PATTERNLOOPENDLESS_ID,
	FX_PATTERNLOOPFLAG_ID,
	FX_GROUP_ID ,
	FX_GROUPSOLO_ID ,
	FX_GROUPMUTE_ID ,
	FX_GROUPREC_ID ,
	FX_PROCESSOR_ID ,
	FX_TRACKSTATUS_ID,
	FX_TRACKIMAGE,

	FX_PATTERNONOFF_ID,
	FX_TRACKONOFF_ID
};

// Frame IDs --------------------------------------------------------------------------------------
enum FrameIDs
{
	ARR_FRAMEID_OVERVIEW,
	ARR_FRAMEID_TEXTMAP,
	ARR_FRAMEID_SIGNATURE,
	ARR_FRAMEID_TEMPOMAP,
	ARR_FRAMEID_PATTERN,
	ARR_FRAMEID_TRACKS,
	ARR_FRAMEID_FOLDER,
	ARR_FRAMEID_PATTERNLIST,
	ARR_FRAMEID_MARKERMAP,
	ARR_FRAMEID_CONTROL
};

// Edit Data ID
enum EA_DataID
{
	TRACKFX_TRANSPOSE=200,
	TRACKFX_VELOCITY,
	TRACKFX_VELOCITY_PATTERN,
	TRACKFX_TRANSPOSE_PATTERN,
	TRACKFX_DELAY
};
#endif
