#ifndef CAMX_AUDIOMIXER
#define CAMX_AUDIOMIXER 1

#include "object.h"

// Reset Channels Flag
#define RESET_CHANNEL_VOLUME 1
#define RESET_CHANNEL_PAN 2
#define RESET_CHANNEL_FX 3
#define RESET_CHANNEL_INSTRUMENTS 4

#define RESETL_CHANNEL_ALL (RESET_CHANNEL_VOLUME|RESET_CHANNEL_PAN|RESET_CHANNEL_FX|RESET_CHANNEL_INSTRUMENTS)

#define RESET_CHANNEL_ALLCHANNELS 1024
#endif