#ifndef CAMX_AUDIOCHANNELTYPES
#define CAMX_AUDIOCHANNELTYPES 1

enum{
	CHANNELTYPE_BUSCHANNEL,
	CHANNELTYPE_DEVICEIN,
	CHANNELTYPE_DEVICEOUT,
	CHANNELTYPE_MASTER,
	LASTCHANNELTYPE,
};

#define LASTSYNTHCHANNEL (CHANNELTYPE_BUSCHANNEL+1)

#endif
