#ifndef CAMX_CAMXGADGETS_H
#define CAMX_CAMXGADGETS_H 1

#define INFOSIZE bitmap.GetTextWidth("WWWWWW")

enum{
	GADGETTYPE_WINDOW,
	GADGETTYPE_BUTTON_TEXT,
	GADGETTYPE_BUTTON_IMAGE,
	GADGETTYPE_SLIDER,
	GADGETTYPE_LISTBOX,
	GADGETTYPE_LISTVIEW,
	GADGETTYPE_CHECKBOX,
	GADGETTYPE_CYCLE,
	GADGETTYPE_TAB,
	GADGETTYPE_STRING,
	GADGETTYPE_INTEGER,
	GADGETTYPE_BUTTON_NUMBER,
	GADGETTYPE_BUTTON_VOLUME,
	GADGETTYPE_TREE,
	GADGETTYPE_TIME,
	GADGETTYPE_DOUBLEBUFFER
};

enum SliderTypes{
	SLIDER_UNKNOWN,
	SLIDER_VERT_ZOOM,
	SLIDER_VERT_NOZOOM,
	SLIDER_HORZ_ZOOM,
	SLIDER_HORZ_NOZOOM
};

#define SIZE_HZOOM_SLIDER 5*maingui->GetFontSizeY()
#define SIZE_VZOOM_SLIDER 4*maingui->GetFontSizeY()

//// GENERAL GADGET IDS ---------------------------
#define SCROLLER_PAGEDOWN 1
#define SCROLLER_PAGEUP 2

#define ZOOMY_MIN 5
#define ZOOMY_MAX 140

enum {
	GADGETID_EDITORSLIDER_HORIZ=16,
	GADGETID_EDITORSLIDER_HORIZZOOM,
	GADGETID_EDITOR_SYNC,
	GADGETID_EDITOR_DATAZOOM,

	GADGETID_EDITORSLIDER_VERT,
	GADGETID_EDITORSLIDER_VERTZOOM,
	GADGETID_EDITOR_MOUSEQUANTIZE,

	// Event global
	GADGETID_EVENTEDITOR_SELECTPATTERN,
	GADGETID_EVENTEDITOR_SELECTPATTERNSOLO,

	// Editor Tool Box
	GADGETID_TOOLBOX_MOUSE,
	GADGETID_TOOLBOX_PENCIL,
	GADGETID_TOOLBOX_CUT,
	GADGETID_TOOLBOX_DELETE,
	GADGETID_TOOLBOX_SELECT,
	GADGETID_TOOLBOX_SPP,
	GADGETID_TOOLBOX_OVERVIEW,
	GADGETID_TOOLBOX_EDIT,
	GADGETID_TOOLBOX_TEXT,
	GADGETID_TOOLBOX_MENU,
	GADGETID_TOOLBOX_MENU2,
	GADGETID_TOOLBOX_CLOSEWINDOW,
	GADGETID_TOOLBOX_RELEASEWINDOW,
	GADGETID_TOOLBOX_MAXWINDOW,
	GADGETID_TOOLBOX_GOTO,
	GADGETID_TOOLBOX_TIMETYPE,
	GADGETID_TOOLBOX_SOLOPLAYBACK,
	GADGETID_TOOLBOX_X,
	GADGETID_TOOLBOX_Y,

	GADGETID_TOOLBOX_QUANTIZE,

	// Editor Control Box
	GADGETID_CONTROLBOX_STOP,
	GADGETID_CONTROLBOX_START,
	GADGETID_CONTROLBOX_RECORD,
	GADGETID_CONTROLBOX_TIME,
	GADGETID_GOTOSONGPOSITION,
	GADGETID_GOTOCYCLELEFT,
	GADGETID_GOTOCYCLERIGHT,

	GADGETID_EDITORBASE
};

#endif