#ifndef CAMX_CHUNKS
#define CAMX_CHUNKS 1

enum{
	CHUNK_CAMX_SONG=1,
	CHUNK_SONGTRACKS,
	CHUNK_SONGTRACKSEND,
	CHUNK_SONGPOINTER,
	CHUNK_SONGGROUPS,
	CHUNK_SONGGROUP,
	CHUNK_SONGSETTINGS,
	CHUNK_SONGPLAYBACK,
	CHUNK_SONGPATTERNLINKLIST,
	CHUNK_SONGPATTERNLINK,
	CHUNK_PROJECT,
	CHUNK_PROJECTSONGS,
	CHUNK_SONGROUTING,
	CHUNK_SONGROUTING_DEVICE,
	CHUNK_SONGROUTING_DEVICE_CHANNELS,
	CHUNK_SONGROUTING_DEVICE_EVENTS,
	CHUNK_SONGROUTING_DEVICE_LOGIC,
	CHUNK_SONGROUTING_DEVICETRACKS,
	CHUNK_SONGROUTING_DEVICETRACK,
	CHUNK_SONG_METRO,
	CHUNK_SONGMETROTRACKS,

	// TRACK
	CHUNK_TRACK=30,
	CHUNK_TRACKMIDIPattern,
	CHUNK_TRACKAUDIOPATTERN,
	CHUNK_TRACKGROUPS,
	CHUNK_TRACKMIDIOutputDeviceS,
	CHUNK_TRACKAUDIOOUTPUTCHANNELS,
	CHUNK_TRACKMIDIINPUTDEVICES,

	CHUNK_MIDIPattern=50,
	CHUNK_TIMETRACK,
	CHUNK_AUDIOPATTERN,
	CHUNK_AUTOMATIONTRACK,
	CHUNK_AUTIOMATIONTRACKHEADER,
	CHUNK_AUTOMATIONTRACKPARAMETERS,
	CHUNK_AUTOMATIONOBJECT,
	CHUNK_AUTOMATIONOBJECTDATA,
	CHUNK_AUTOMATIONOBJECTSPECIALDATA,
	CHUNK_AUTOMATIONTRACKPARAMETER,

	CHUNK_TRACKPROCESSOR=70,
	CHUNK_AUDIOCROSSFADES,
	CHUNK_AUDIOCROSSFADE,

	// PATTERN
	CHUNK_MIDIEVENTS=80,
	CHUNK_AUDIOEVENT,
	CHUNK_PATTERNFX,
	CHUNK_PATTERNFX_QUANTIZE,
	CHUNK_AUDIOEVENT_REGION,
	CHUNK_MIDIEVENTSFLAGS,
	CHUNK_AUDIOEVENT_EVENTREGION,

	// GLOBAL
	CHUNK_MAINAUDIO=100,
	CHUNK_PROCESSOR,
	CHUNK_PROCESSORMODULE,
	CHUNK_PROCESSORIO,

	// HARDWARE
	CHUNK_AUDIODEVICE=500,

	CHUNK_AUDIODEVICES=502,
	CHUNK_AUDIOHARDWARE,
	CHUNK_AUDIODEVICEINPUTPORTS,
	CHUNK_AUDIODEVICEOUTPUTPORTS,

	// IO-Files
	CHUNK_AUDIOHDFILES=530,
	CHUNK_AUDIOHDFILE,
	CHUNK_AUDIOHDREGIONS,
	CHUNK_AUDIOHDREGION,

	CHUNK_MIDIDEVICES=550,
	CHUNK_MIDIOUTDEVICES,
	CHUNK_MIDIINDEVICES,
	CHUNK_MIDIOUTDEVICE,

	// AUDIO
	CHUNK_AUDIOSYSTEM=600,
	CHUNK_AUDIOCHANNEL,
	CHUNK_AUDIOCHANNEL_SEND,
	CHUNK_AUDIOHARDWARECHANNELS_OUTPUT=605,
	CHUNK_AUDIOHARDWARECHANNELS_INPUT,

	CHUNK_AUDIOCHANNELINSERTEFFECT=610,
	CHUNK_AUDIOIOFX,
	CHUNK_AUDIOCHANNELEFFECTS, 
	CHUNK_AUDIOCHANNELINSTRUMENTS,
	CHUNK_AUDIOCHANNELEFFECT,
	CHUNK_AUDIOCHANNELINSTRUMENT,
	CHUNK_AUDIOHARDWARECHANNELEFFECTS,
	OLD_CHUNK_AUDIOMIXERGROUPS,
	CHUNK_AUDIOCHANNELEFFECTDATACHUNK,
	CHUNK_AUDIOEFFECT_SEPERATEOUTS,

	// Audio Static
	CHUNK_AUDIOSTATIC_MISC=650,
	CHUNK_AUDIOSTATIC_VOLUME,
	CHUNK_AUDIOSTATIC_PAN,
	CHUNK_PANLAW,
	CHUNK_AUDIOSTATIC_MISCAUTOMATION,
	CHUNK_PATTERNVOLUMECURVE,

	// MIDI 
	CHUNK_MIDIIOFX=800,

	// MISC
	CHUNK_TRACKFX=1200,
	CHUNK_TEMPOMAP,
	CHUNK_SIGNATUREMAP,
	CHUNK_QUANTIZEFX,
	CHUNK_TEXTANDMARKER,
	CHUNK_MIDIEFFECTS,

	CHUNK_MIDIGROOVES=1307,
	CHUNK_GROOVE,
	CHUNK_GROOVEELEMENTHEADER,
	CHUNK_GROOVEELEMENT,

	CHUNK_TEXT_=1410,
	CHUNK_MARKER,
	CHUNK_TRACKPOINTER,
	CHUNK_DRUMMAPHEADER,
	CHUNK_DRUMMAP,
	CHUNK_DRUMTRACK,
	CHUNK_WAVEMAPHEADER,
	CHUNK_WAVEMAP,
	CHUNK_WAVETRACK,

	CHUNK_MIDIFILTER=1500,
	CHUNK_KEYMAP,
	EX_CHUNK_MIDIPROGRAM, // DEAD
	CHUNK_MIDIPROGRAMNEW,

	// Settings
	CHUNK_SETTINGSPOINTER=1600,
	CHUNK_SETTINGSDEFAULT,
	OLD_CHUNK_SETTINGSFRAMES,
	CHUNK_SETTINGSMIDIOUTFILTER,
	CHUNK_SETTINGSVST,
	CHUNK_SETTINGSAUDIODIR,
	CHUNK_VSTSORT,
	CHUNK_SETTINGSPROJECTS,
	CHUNK_VSTSORTFX,
	CHUNK_SETTINGSWINDOWPOSITIONS,
	CHUNK_VSTSORTFX64,
	CHUNK_SETTINGSVST2,
	CHUNK_SETTINGSVST3,
	OLD_CHUNK_SETTINGSVST364,

	// MIDI Devices Info
	CHUNK_SETTINGSMIDIOUTDEVICEINFO=1700,
	CHUNK_SETTINGSMIDIINDEVICEINFO,
	CHUNK_SETTINGSMIDIOUTDEVICE,
	CHUNK_SETTINGSMIDIINDEVICE,

	CHUNK_SETTINGSMIDIINPUTPORTS,
	CHUNK_SETTINGSMIDIINPUTPORT,

	CHUNK_SETTINGSMIDIOUTPUTPORTS,
	CHUNK_SETTINGSMIDIOUTPUTPORT,

	CHUNK_SETTINGSHEADER=1801,
	CHUNK_SETTINGSOSSCREENS,
	OLD_CHUNK_SETTINGSOSSCREEN,
	CHUNK_SETTINGSGUIWINDOWS,
	CHUNK_SETTINGSGUIWINDOW,
	CHUNK_SETTINGSPROCESSOR,
	CHUNK_SETTINGSDRUMMAP,
	CHUNK_FORM
};

#endif