#ifndef CAMX_COLOURS_H
#define CAMX_COLOURS_H 1

enum Colours
{
	COLOUR_BLACK,
	COLOUR_CYCLE,
	COLOUR_CYCLE_PIANO,
	COLOUR_WHITE,
	COLOUR_BLUE,
	COLOUR_GREEN,
	COLOUR_RED,
	COLOUR_ORANGE,
	COLOUR_ERROR,
	COLOUR_RECORD,
	COLOUR_RECORDCHILDS,
	COLOUR_GREY,
	COLOUR_GREY_LIGHT,
	COLOUR_BACKGROUND,
	COLOUR_GREY_DARK,
	COLOUR_BLUE_LIGHT,
	COLOUR_BLUE_LIGHT2,
	COLOUR_YELLOW,
	COLOUR_YELLOW_LIGHT,
	COLOUR_BLACK_LIGHT,
	COLOUR_RED_LIGHT,
	COLOUR_MIDI_BACKGROUND,
	COLOUR_MIDI_BACKGROUND2,
	COLOUR_MIDI_BACKGROUND_SELECTED,
	COLOUR_AUDIO_BACKGROUND,
	COLOUR_AUDIO_BACKGROUND_SELECTED,
	COLOUR_AUDIOHEADER,
	COLOUR_AUDIORECORDHEADER,
	COLOUR_AUDIORECORD,

	COLOUR_SUBTRACK_BACKGROUND,
	COLOUR_UNUSED,
	COLOUR_OBJECT,
	COLOUR_11x1,
	COLOUR_WHITE_LIGHT,
	COLOUR_BACKGROUND2,
	COLOUR_MOUSEOVER,
	COLOUR_MOUSEOVERSTATIC,
	COLOUR_MOUSEOVERINDEX,
	COLOUR_MOUSEEDITINDEX,

	COLOUR_GADGETBACKGROUND,
	COLOUR_GADGETBACKGROUNDSTATIC,
	COLOUR_GADGETBACKGROUNDSYSTEM,
	COLOUR_GADGETBACKGROUNDNOTACTIVE,
	COLOUR_GADGETBACKGROUNDOSBUTTON,
	COLOUR_TEXTCONTROL,
	COLOUR_GADGETBACKGROUNDLISTBOX,
	COLOUR_GADGETBACKGROUNDEDIT,
	COLOUR_GADGETBACKGROUNDSTRINGINT,

	COLOUR_BORDERGADGET,
	COLOUR_BORDERGADGETLEFT,
	COLOUR_BORDERGADGETRIGHT,
	COLOUR_INFOBORDER,

	// Window
	COLOUR_BACKGROUNDDIALOG,
	COLOUR_BACKGROUNDWINDOWS,
	COLOUR_NOMOUSEOVER,
	COLOUR_BACKGROUNDTOOLBAR,
	COLOUR_TEXT,
	COLOUR_LENGTH,
	COLOUR_TEXT_INFO,
	COLOUR_GADGETTEXT_MOUSEOVER,
	COLOUR_GADGETTEXT,
	COLOUR_SAMPLEBACKGROUND,
	COLOUR_BACKGROUNDSIZER,
	COLOUR_BACKGROUNDFORMTEXT,
	COLOUR_BACKGROUNDFORMTEXT_SELECTED,

	COLOUR_BACKGROUNDTEXTTIME,
	COLOUR_BACKGROUNDFORMTEXT_HIGHLITE,
	COLOUR_BACKGROUNDFORMTEXT_HIGHLITE_SELECTED,

	COLOUR_BACKGROUNDEDITOR_GFX_HIGHLITE,
	COLOUR_BACKGROUNDEDITOR_GFX,
	COLOUR_BACKGROUNDEDITOR_GFX_MUTED,
	COLOUR_BACKGROUNDEDITOR_GFX_MUTEDHIGHLITE,

	COLOUR_BACKGROUNDPATTERN_MUTED,

	COLOUR_METROTRACK,
	COLOUR_FRONT_SELECTED,
	COLOUR_FRONT_NOTSELECTED,

	COLOUR_PIANO_BLACK_BACKGROUND,
	COLOUR_PIANO_WHITE_BACKGROUND,
	COLOUR_PIANO_WHITE_BACKGROUND_C,
	COLOUR_PIANO_WHITE_BACKGROUND_F,

	COLOUR_OVERVIEW_BACKGROUND,
	COLOUR_OVERVIEWCYCLE,
	COLOUR_OVERVIEWOBJECT,
	COLOUR_OVERVIEWFOCUSOBJECT,

	COLOUR_RASTER1,
	COLOUR_RASTER2,

	COLOUR_BUSCHANNEL,
	COLOUR_BUSCHANNELSELECTED,

	COLOUR_MASTERCHANNEL,

	COLOUR_TOGGLEON,
	COLOUR_TOGGLEOFF,
	COLOUR_GROUPTOGGLEON,
	COLOUR_GROUPTOGGLEOFF,

	COLOUR_MUTE,
	COLOUR_MIDIVUBACKGROUND,
	COLOUR_MIDIVUFOREGROUND,
	COLOUR_MIDIVUBACKGROUND_INPUT,
	COLOUR_MIDIVUFOREGROUND_INPUT,
	COLOUR_DEVICEIN,
	COLOUR_DEVICEOUT,
	COLOUR_GADGETBACKGROUNDNUMBER,
	COLOUR_GAGDGETFOCUS,

	COLOUR_TIME,
	COLOUR_SMPTE,
	COLOUR_SMPTELIGHT,
	COLOUR_SAMPLES, 

	COLOUR_LASSO,
	COLOUR_INPUTMONITOR_BACKGROUND,
	COLOUR_INPUTMONITOR_BACKGROUND_ACTIVE,
	COLOUR_INPUT1,
	COLOUR_INPUT2,
	COLOUR_INPUT3,
	COLOUR_INPUTMONITOR_LINEMAX,
	
	COLOUR_THRUON_BACKGROUND,

	COLOUR_BACKGROUNDCHILD,
	COLOUR_BACKGROUNDCHILD_HIGHLITE,

	COLOUR_GADGETBACKGROUNDPUSHBUTTON,
	COLOUR_FOCUSOBJECT,
	COLOUR_FOCUSOBJECT_SELECTED,
	COLOUR_TIMEPOSITION,
	COLOUR_TIMEPOSITIONMOUSEMOVE,
	COLOUR_SENDPOST,
	COLOUR_SENDPRE,
	COLOUR_AUDIOINVOLUME_BACKGROUND,
	COLOUR_AUDIOTYPE_BACKGROUND,
	COLOUR_PIANOKEY,
	COLOUR_BORDER_OBJECTMOVING,
	COLOUR_AUDIOOUTPEAK,
	
	COLOUR_AUDIOOUTPEAK_SELECTED,
	COLOUR_AUDIOOUTPEAK_BACKGROUND,

	COLOUR_AUDIOOUTPEAK_SELECTED_GREEN,
	COLOUR_AUDIOOUTPEAK_GREEN,

	COLOUR_FOLDERBORDER,
	COLOUR_PATTERNBORDER,

	COLOUR_AUTOMATIONTRACKS,
	COLOUR_AUTOMATIONTRACKSUSED,

	COLOUR_AUTOMATIONSCALE,
	COLOUR_AUTOMATIONSCALE2,

	COLOUR_BACKGROUNDAUTOMATION,
	COLOUR_BACKGROUNDAUTOMATION_HIGHLITE,
	COLOUR_AUTOMATIONPATTERNBACKGROUND,

	COLOUR_SAMPLESPAINT,
	COLOUR_BACKGROUNDAUTOMATIONARRANGE,

	COLOUR_NOREALPATTERN,
	COLOUR_BACKGROUND_TEXT,

	COLOUR_SYNC,
	COLOUR_FROZEN,

	COLOUR_AUDIO_BACKGROUND_LOOP,
	COLOUR_MIDI_BACKGROUND_LOOP,

	COLOUR_RECSETTINGSON,
	COLOUR_SELECTEDARTRACK,
	
	LASTCOLOUR
};

#define COLOUR_SELECTED COLOUR_GREY

#endif