#ifndef CAMX_EDITORTYPES_H
#define CAMX_EDITORTYPES_H 1

enum{
	EDITORTYPE_ARRANGE,
	
	EDITORTYPE_ARRANGELIST,
	EDITORTYPE_ARRANGEFX,
	EDITORTYPE_ARRANGEFXMIDI,
	EDITORTYPE_ARRANGEFXMETRO,
	EDITORTYPE_ARRANGEFXAUDIO,
	EDITORTYPE_ARRANGEFXQUANT,
	EDITORTYPE_ARRANGEFXPATTERN,

	EDITORTYPE_EVENT,
	EDITORTYPE_PIANO,
	EDITORTYPE_PIANOWAVE,
	EDITORTYPE_WAVE,
	
	EDITORTYPE_DRUM,
	EDITORTYPE_DRUMLIST,
	EDITORTYPE_DRUMFX,

	EDITORTYPE_SCORE,
	EDITORTYPE_AUDIOMIXER,
	EDITORTYPE_AUDIOEDITOR,
	EDITORTYPE_GROOVE,
	EDITORTYPE_SAMPLE,
	EDITORTYPE_EDITDATA,
	EDITORTYPE_TRANSPORT,
	
	EDITORTYPE_SETTINGS,
	EDITORTYPE_SETTINGS_AUDIO,
	EDITORTYPE_SETTINGS_PLUGINGS,
	EDITORTYPE_SETTINGS_VSTFX,
	EDITORTYPE_SETTINGS_CRASHEDPLUGIN,
	EDITORTYPE_SETTINGS_MIDI,
	EDITORTYPE_SETTINGS_METRONOM,
	EDITORTYPE_SETTINGS_MIDIINPUT,
	EDITORTYPE_SETTINGS_MIDIOUTPUT,

	EDITORTYPE_SETTINGS_FILES,
	EDITORTYPE_SETTINGS_AUDIOINPUT,
	EDITORTYPE_SETTINGS_AUDIOOUTPUT,
	EDITORTYPE_SETTINGS_AUDIOFILES,
	EDITORTYPE_SETTINGS_PROJECT,
	EDITORTYPE_SETTINGS_PROJECTAUDIO,
	EDITORTYPE_SETTINGS_PROJECTGUI,
	EDITORTYPE_SETTINGS_SONG,
	EDITORTYPE_SETTINGS_SONGSYNC,
	EDITORTYPE_SETTINGS_UI,
	EDITORTYPE_SETTINGS_KEYS,
	EDITORTYPE_SETTINGS_AUTOMATION,

	EDITORTYPE_AUDIOMANAGER,
	EDITORTYPE_QUANTIZEEDITOR,
	EDITORTYPE_AUDIOMASTER,
	EDITORTYPE_AUDIOFREEZE,
	EDITORTYPE_MIDIFILTER,
	EDITORTYPE_PLUGIN_VSTEDITOR,
	EDITORTYPE_PLUGINLISTEDITOR,

	EDITORTYPE_TEMPO,
	EDITORTYPE_TEMPOLIST,

	EDITORTYPE_TOOLBOX,
	
	EDITORTYPE_RECORDEDITOR,
	EDITORTYPE_SYNCEDITOR,
	EDITORTYPE_KEYBOARD,
	EDITORTYPE_PLUGIN_INTERN,
	EDITORTYPE_TEXT,
	EDITORTYPE_GROUP,
	EDITORTYPE_PROCESSOR,
	EDITORTYPE_PLAYER,
	EDITORTYPE_KEYMAP,
	EDITORTYPE_MARKER,
	EDITORTYPE_BIGTIME,
	EDITORTYPE_RMG,
	EDITORTYPE_LIBRARY,
	EDITORTYPE_CAMXINFO,
	EDITORTYPE_MONITOR,
	EDITORTYPE_CREATETRACKS,
	EDITORTYPE_CREATEBUS,
	EDITORTYPE_CREATEAUTOMATIONTRACKS,
	EDITORTYPE_PEAKWINDOW,
	EDITORTYPE_PROCESSORMODULE,
	EDITORTYPE_UPDATE,
	EDITORTYPE_CROSSFADE,
	EDITORTYPE_CPU,
	EDITORTYPE_SAMPLEREGIONLIST,
	EDITORTYPE_TEMPOTAP,

	EDITORTYPE_LASTEDITOR // DONT USE
};

#endif