#ifndef CAMX_IMAGESDEFINES_H
#define CAMX_IMAGESDEFINES_H 1

// IMAGE 0=no image

enum ImageDefines{
	IMAGE_RECBUTTON_ON,
	IMAGE_RECBUTTON_OFF,
	IMAGE_CYCLEBUTTON_ON,
	IMAGE_CYCLEBUTTON_OFF,
	IMAGE_TRACKMUTEON,
	IMAGE_TRACKMUTEOFF,
	IMAGE_TRACKRECORDON,
	IMAGE_TRACKRECORDOFF,
	IMAGE_SOLOBUTTON_ON,
	IMAGE_SOLOBUTTON_OFF,
	IMAGE_RECBUTTON_PUNCHIN_ON,
	IMAGE_RECBUTTON_PUNCHIN_OFF,
	IMAGE_RECBUTTON_PUNCHOUT_ON,
	IMAGE_RECBUTTON_PUNCHOUT_OFF,
	IMAGE_STOPBUTTON_ON,
	IMAGE_STOPBUTTON_OFF,
	//IMAGE_MIDICHANNEL,
	//IMAGE_AUDIOMIXER,
	IMAGE_BYPASS_OFF,
	IMAGE_BYPASS_ON,
	IMAGE_TRACKSOLOON,
	IMAGE_TRACKOTHERTRACKSOLO,
	IMAGE_TRACKSOLOOFF,
	IMAGE_PLAYBUTTON_ON,
	IMAGE_PLAYBUTTON_OFF,
	
	IMAGE_PLAYBUTTONCLIP_OFF,
	IMAGE_PLAYBUTTONCLIP_ON,

	IMAGE_RECSTEPBUTTON_ON,
	IMAGE_TOOLBOX_MOUSE, // Toolbox
	IMAGE_TOOLBOX_PENCIL,
	IMAGE_TOOLBOX_CUT,
	IMAGE_TOOLBOX_DELETE,
	IMAGE_TOOLBOX_SELECT,
	IMAGE_TOOLBOX_EDIT,
	IMAGE_TOOLBOX_PENCIL_NSEL,
	IMAGE_TOOLBOX_CUT_NSEL,
	IMAGE_TOOLBOX_DELETE_NSEL,
	IMAGE_TOOLBOX_SELECT_NSEL,
	IMAGE_TOOLBOX_EDIT_NSEL,
	IMAGE_TOOLBOX_MOUSE_NSEL,

	IMAGE_PLAYBUTTON_SMALL_OFF,
	IMAGE_PLAYBUTTON_SMALL_ON,
	IMAGE_STOPBUTTON_SMALL_OFF,
	IMAGE_STOPBUTTON_SMALL_ON,
	IMAGE_RECORDBUTTON_SMALL_OFF,
	IMAGE_RECORDBUTTON_SMALL_ON,
	IMAGE_PLAYBUTTONCROSSFADE_SMALL_ON,

	IMAGE_AUDIOEFFECT,
	IMAGE_MIDIEFFECT,

	// SMPTE
	IMAGE_SAMPLES_SMALL,

	// Sample Editor
	IMAGE_SEPLAYREGION_SMALL,
//	IMAGE_SEPLAYREGIONEND_SMALL,
//	IMAGE_SEPLAYREGIONSTART_SMALL,
//	IMAGE_SEPLAYREGIONSTARTSEEK_SMALL,

//	EX_IMAGE_LOGO,
	IMAGE_BKG16,
	IMAGE_BKG32,
	IMAGE_BKG64,

//	IMAGE_TIME_ON,
//	IMAGE_TIME_OFF,

//	IMAGE_PLAY_ON,
//	IMAGE_PLAY_OFF,
	IMAGE_PREVMARKER,
	IMAGE_NEXTMARKER,
	IMAGE_SPP0,
	IMAGE_SPQN,
	IMAGE_FF,
	IMAGE_REW,

	IMAGE_CLOSEWINDOW,
	IMAGE_WINDOWUP,
	IMAGE_WINDOWDOWN,

	LAST_IMAGE
};
#endif