
#ifdef WIN32
// WINDOWS ...
#define KEYSPACE VK_SPACE
#define KEYF1 VK_F1
#define KEYF2 VK_F2
#define KEYF3 VK_F3
#define KEYF4 VK_F4
#define KEYF5 VK_F5
#define KEYF6 VK_F6
#define KEYF7 VK_F7
#define KEYF8 VK_F8
#define KEYF9 VK_F9
#define KEYF10 VK_F10
#define KEYF11 VK_F11
#define KEYF12 VK_F12

#define KEYDELETE VK_DELETE
// end WINDOWS

// KEYS
#define KEY_CURSORLEFT VK_LEFT
#define KEY_CURSORRIGHT VK_RIGHT
#define KEY_CURSORUP VK_UP
#define KEY_CURSORDOWN VK_DOWN
#define KEY_RETURN VK_RETURN
#define KEY_ESCAPE VK_ESCAPE

#define KEY_LEFT10 VK_NUMPAD4
#define KEY_RIGHT10 VK_NUMPAD6
#define KEY_UP10 VK_NUMPAD8
#define KEY_DOWN10 VK_NUMPAD2
#define KEY_KEY0_10 VK_NUMPAD0

#define KEY_TAB VK_TAB
#define KEY_MINUS10 VK_SUBTRACT
#define KEY_ADD10 VK_ADD
#define KEY_DIVIDE VK_DIVIDE
#define KEY_MULTIPLY VK_MULTIPLY

#
#endif

