#ifndef CAMX_MENUDEFINES_H
#define CAMX_MENUDEFINES_H 1

#include "defines.h"

#define EDITOR_EDITOREVENT MENU_ID_START+1
#define EDITOR_EDITORWAVE MENU_ID_START+2
#define EDITOR_EDITORDRUM MENU_ID_START+3
#define EDITOR_EDITORPIANO MENU_ID_START+4
#define EDITOR_EDITORTRANSPORT MENU_ID_START+5

// Quantize
#define EDITOR_EDITORQUANTIZEMEASURE MENU_ID_START+10
#define EDITOR_EDITORQUANTIZE1 MENU_ID_START+11
#define EDITOR_EDITORQUANTIZE12 MENU_ID_START+12
#define EDITOR_EDITORQUANTIZE14 MENU_ID_START+13
#define EDITOR_EDITORQUANTIZE18 MENU_ID_START+14
#define EDITOR_EDITORQUANTIZE116 MENU_ID_START+15
#define EDITOR_EDITORQUANTIZEFREE MENU_ID_START+16
 
// Window Display

#define EDITOR_DISPLAYMEASURE MENU_ID_START+30
#define EDITOR_DISPLAYSMPTE24 MENU_ID_START+31
#define EDITOR_DISPLAYSMPTE25 MENU_ID_START+32
#define EDITOR_DISPLAYSMPTE297 MENU_ID_START+33
#define EDITOR_DISPLAYSMPTE30 MENU_ID_START+34

#define MENU_UNDO MENU_ID_START+50
#define MENU_CUT MENU_ID_START+51
#define MENU_COPY MENU_ID_START+52
#define MENU_PASTE MENU_ID_START+53
#define MENU_DELETE MENU_ID_START+54
#define MENU_REDO MENU_ID_START+55

#endif