#ifndef CAMX_OBJIDS_H
#define CAMX_OBJIDS_H

enum IDs{
	OBJ_SONG,
	OBJ_TRACK,
	OBJ_AUDIOCHANNEL,
	OBJ_AUTOMATIONTRACK,
	OBJ_PATTERN,
	OBJ_EVENTS,
	OBJ_SELECTPATTERN,
	OBJ_WAVETRACK,
	OBJ_AUDIOPATTERN,
	OBJ_MIDIPattern,
	OBJ_NOTEOFF,
	OBJ_SYSEXEND,
	OBJ_NOTE,
	OBJ_PROGRAM,
	OBJ_CONTROL,
	OBJ_PITCHBEND,
	OBJ_SYSEX,
	OBJ_CHANNELPRESSURE,
	OBJ_POLYPRESSURE,
	OBJ_AUDIOHDFILE,
	OBJ_AUDIOREGIONFILE,
	OBJ_AUDIOEVENT,
	OBJ_ICDEVENT,
	OBJ_EFFECTLIST,
	OBJ_MIDIAUTO,
	OBJ_AUDIOINTERN,
	OBJ_AUDIOVST,
	OBJ_AUDIOREGION
};

#endif
