#ifndef WAVEEDITORDEFINES

#define WAVEEDITORDEFINES

// Frame IDs
#define WAVE_FRAMEID_TRACKS 0
#define WAVE_FRAMEID_EVENTS 1

// Init Default
#define WAVE_HEADERPOSITIONX 150
// #define WAVE_HEADERPOSITIONY 4

//#define WAVE_TRACKPOSITIONX 5

// #define WAVE_KEYPOSITIONY 60

#define WAVE_NOTESPOSITIONX 150
// #define WAVE_NOTESPOSITIONY 60

#define WAVEMENU_START MENU_ID_START+50	

// STANDARD MENU
#define WAVEMENU_CREATENEWTRACK WAVEMENU_START+10

// POP Menus
#define WAVE_POPMENU_ADDWAVETRACK WAVEMENU_START+200
#define WAVE_POPMENU_DELETEWAVETRACK WAVEMENU_START+201

// Gadgets -------------------------------------------
#define FXGADGETID_START GADGET_ID_START+50

#define FX_WAVE_TRACKNAME_ID FXGADGETID_START+5
#define FX_WAVE_TRACKSTATUS_ID FXGADGETID_START+6
#define FX_WAVE_TRACKDATA1_ID FXGADGETID_START+7
#define FX_WAVE_TRACKDATA2_ID FXGADGETID_START+8
#define FX_WAVE_TRACKCHANNEL_ID FXGADGETID_START+9 // MIDI Channel

#endif
