/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Martin Endres
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_sub                                 0
#define GD_add                                 1
#define GD_zoomi                               2
#define GD_test                                3
#define GD_zorro                               4
#define GD_edscale                             5

#define GDX_sub                                0
#define GDX_add                                1
#define GDX_zoomi                              2
#define GDX_test                               3
#define GDX_zorro                              4
#define GDX_edscale                            5

#define So_CNT 6

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;



extern int SetupScreen( void );
extern void CloseSoDownScreen( void );
extern int OpenSoWindow( void );
extern void CloseSoWindow( void );
